### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by simobit** [Squirrel-Network/api_nebula#1]
**How to repeat this if:**
Open https://nebula.hersel.it/blacklist?tgid=SOMELETTERS

**Result:**
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Summary:**
When you enter letters in tgid parameter server returns error without handling it with API

**Comment by BluLupo** [comment]
@simobit Thanks for reporting, I'll fix this bug
