### ISSUE TITLE
/blacklist 404 Error

### ISSUE THREAD

**Issue by Moppy-cloud** [Squirrel-Network/api_nebula#2]
I tried opening https://domain.ext/blacklist without any GET parameters, and it returns a 404 Errore not in JSON.[
![Schermata 2020-12-14 alle 22 47 15](https://user-images.githubusercontent.com/76014643/102139632-6195fe80-3e5e-11eb-9f92-7d82cad3fa14.png)
](url)

**Comment by Moppy-cloud** [comment]
The issue was also found in all others methods

**Comment by BluLupo** [comment]
https://nebula.hersel.it/blacklist?tgid=1480224243

**Comment by Moppy-cloud** [comment]
Sorry, I was trying do that on http://squirrel-network.online/blacklist
