### ISSUE TITLE
refactor endpoint in RESTish fashion

### ISSUE THREAD

**Issue by mdnmdn** [Squirrel-Network/api_nebula#7]
| ACTUAL | REFACTORED |
| ---------| --------------|
| add_blacklist | POST /blacklist/ |
| user_by_id | GET /user/@tg_id |
| delete_user | DELETE /user/@tg_id |

**Comment by BluLupo** [comment]
Yes approved

**Comment by SteelManITA** [comment]
Ok for post, but delete should be with id and not tgid beacause if we
extend nebula to other platform (other than Telegram, like slack or
discord) It doesn't work anymore.

So we can
GET /users with tgid filter, and then DELETE /users/:id, with id returned
by GET.

Furthermore resources should be plural (users, groups, blacklist)


Il mer 26 mag 2021, 00:00 BluLupo ***@***.***> ha scritto:
